## @defgroup Analyses-Mission-Segments-Descent Descent
# Segments for descending flight
# @ingroup Analyses-Mission-Segments


from Constant_Speed_Constant_Angle import Constant_Speed_Constant_Angle
from Constant_Speed_Constant_Angle_Noise import Constant_Speed_Constant_Angle_Noise
from Constant_Speed_Constant_Rate import Constant_Speed_Constant_Rate
from Constant_Speed_Constant_Rate_VSP import Constant_Speed_Constant_Rate_VSP
from Linear_Mach_Constant_Rate import Linear_Mach_Constant_Rate
from Constant_EAS_Constant_Rate import Constant_EAS_Constant_Rate
from Unknown_Throttle import Unknown_Throttle
from Unknown_Throttle_VSP import Unknown_Throttle_VSP
